
import type { User, Listing, ListingSeller, Review, Transaction } from '@/lib/types';
import { PlaceHolderImages } from '@/lib/placeholder-images';

const findImage = (id: string) => PlaceHolderImages.find(img => img.id === id)?.imageUrl || '';

export const dummyUsers: User[] = [
  {
    id: 'user_1',
    uid: 'user_1',
    name: 'Priya Sharma',
    email: 'priya@iitb.ac.in',
    college: 'IIT Bombay',
    verified: true,
    profilePictureUrl: findImage('user-1') || "https://picsum.photos/seed/user1/200",
    bio: 'Budding software engineer and ML enthusiast. Selling my old engineering books and notes. Let\'s connect!',
    skills: ['Python', 'C++', 'Machine Learning', 'Data Structures'],
    following: ['user_2'],
    followers: ['user_3', 'user_2'],
    createdAt: new Date().toISOString(),
    rating: 4.8,
    totalSales: 16,
    sellerLevel: 'Gold',
    xpPoints: 1350,
    badges: ['Top Seller', 'Quick Responder'],
    nexusCredits: 150,
  },
  {
    id: 'user_2',
    uid: 'user_2',
    name: 'Rohan Mehta',
    email: 'rohan@christuniversity.in',
    college: 'Christ University, Bangalore',
    verified: true,
    profilePictureUrl: findImage('user-2') || "https://picsum.photos/seed/user2/200",
    bio: 'BBA student with a passion for marketing and graphic design. Offering freelance design services for college fests and events.',
    skills: ['Graphic Design', 'Canva', 'Social Media Marketing'],
    following: ['user_1'],
    followers: ['user_1', 'user_3'],
    createdAt: new Date().toISOString(),
    rating: 4.9,
    totalSales: 26,
    sellerLevel: 'Platinum',
    xpPoints: 2200,
    badges: ['Creative Pro', 'Community Helper'],
    nexusCredits: 220,
  },
  {
    id: 'user_3',
    uid: 'user_3',
    name: 'Ananya Singh',
    email: 'ananya@du.ac.in',
    college: 'Delhi University',
    verified: true,
    profilePictureUrl: findImage('user-3') || "https://picsum.photos/seed/user3/200",
    bio: 'Aspiring journalist and avid reader. Selling curated bundles of pre-loved novels and providing proofreading services.',
    skills: ['Writing', 'Editing', 'Content Creation'],
    following: ['user_1', 'user_2'],
    followers: [],
    createdAt: new Date().toISOString(),
    rating: 4.7,
    totalSales: 32,
    sellerLevel: 'Gold',
    xpPoints: 1950,
    badges: ['Bookworm', 'Top Reviewer'],
    nexusCredits: 175,
  },
  {
    id: 'user_4',
    uid: 'user_4',
    name: 'Vikram Reddy',
    email: 'vikram@iitm.ac.in',
    college: 'IIT Madras',
    verified: true,
    profilePictureUrl: findImage('user-4') || "https://picsum.photos/seed/user4/200",
    bio: 'Mechanical engineer and robotics geek. Selling old components and offering CAD tutoring.',
    skills: ['AutoCAD', 'SolidWorks', 'Robotics'],
    following: [],
    followers: [],
    createdAt: new Date().toISOString(),
    rating: 4.6,
    totalSales: 8,
    sellerLevel: 'Silver',
    xpPoints: 800,
    badges: ['Tech Guru'],
    nexusCredits: 75,
  },
  {
    id: 'user_5',
    uid: 'user_5',
    name: 'Sneha Rao',
    email: 'sneha@nift.ac.in',
    college: 'NIFT Delhi',
    verified: true,
    profilePictureUrl: findImage('user-5') || "https://picsum.photos/seed/user5/200",
    bio: 'Fashion design student. Selling custom sketches and thrifted clothing.',
    skills: ['Fashion Design', 'Sketching', 'Thrifting'],
    following: [],
    followers: [],
    createdAt: new Date().toISOString(),
    rating: 4.8,
    totalSales: 12,
    sellerLevel: 'Silver',
    xpPoints: 1100,
    badges: ['Fashionista'],
    nexusCredits: 110,
  }
];

// Helper to create denormalized seller objects
const getListingSeller = (userId: string): ListingSeller => {
    const user = dummyUsers.find(u => u.id === userId);
    if (!user) throw new Error(`User not found for ID: ${userId}`);
    return {
        id: user.id,
        name: user.name,
        profilePictureUrl: user.profilePictureUrl
    };
};


export const dummyListings: Listing[] = [
  {
    id: 'listing_1',
    title: 'GATE CSE Digital Preparation Notes',
    description: 'Comprehensive and well-organized digital notes for all Computer Science subjects for the GATE exam. Includes solved previous year papers.',
    category: 'Digital Products',
    price: 499.00,
    mediaUrl: findImage('listing-gate-notes') || "https://picsum.photos/seed/listing1/600/400",
    mediaType: 'image',
    sellerId: 'user_1',
    seller: getListingSeller('user_1'),
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    college: 'IIT Bombay',
  },
  {
    id: 'listing_2',
    title: 'Graphic Design for College Fests',
    description: 'Need posters, social media posts, or logos for your college event? I provide professional design services at student-friendly prices. Contact for a quote.',
    category: 'Services',
    price: 999.00,
    mediaUrl: findImage('listing-fest-design') || "https://picsum.photos/seed/listing2/600/400",
    mediaType: 'image',
    sellerId: 'user_2',
    seller: getListingSeller('user_2'),
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    college: 'Christ University, Bangalore',
  },
  {
    id: 'listing_3',
    title: 'Gently Used Engineering Textbooks (1st Year)',
    description: 'Complete set of first-year engineering textbooks for CSE. Includes books for Physics, Chemistry, Maths, and C++. All in excellent condition.',
    category: 'Physical Products',
    price: 1500.00,
    mediaUrl: findImage('listing-engg-books') || "https://picsum.photos/seed/listing3/600/400",
    mediaType: 'image',
    sellerId: 'user_1',
    seller: getListingSeller('user_1'),
    status: 'sold',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    college: 'IIT Bombay',
  },
  {
    id: 'listing_4',
    title: 'Need Teammate for Smart India Hackathon',
    description: 'Looking for a backend developer (Node.js/Django) for our team for the Smart India Hackathon. We have a great idea for a healthcare solution.',
    category: 'Community/Collaboration',
    price: 0.00,
    mediaUrl: findImage('listing-hackathon') || "https://picsum.photos/seed/listing4/600/400",
    mediaType: 'image',
    sellerId: 'user_1',
    seller: getListingSeller('user_1'),
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    college: 'IIT Bombay',
  },
  {
    id: 'listing_5',
    title: 'Homemade North Indian Tiffin Service',
    description: 'Delicious and healthy home-cooked North Indian meals delivered to your hostel or PG. Weekly and monthly plans available. (Only for IITB campus)',
    category: 'Services',
    price: 120.00,
    mediaUrl: findImage('listing-tiffin') || "https://picsum.photos/seed/listing5/600/400",
    mediaType: 'image',
    sellerId: 'user_3',
    seller: getListingSeller('user_3'),
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    college: 'Delhi University',
  },
  {
    id: 'listing_8',
    title: 'Used Bicycle for Campus Commute',
    description: 'A Hero cycle in good working condition. Perfect for getting around the large DU campus. Minor scratches but runs smoothly. Price is negotiable.',
    category: 'Physical Products',
    price: 2000,
    mediaUrl: findImage('listing-bicycle') || "https://picsum.photos/seed/listing8/600/400",
    mediaType: 'image',
    sellerId: 'user_3',
    seller: getListingSeller('user_3'),
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
    college: 'Delhi University',
  },
  {
    id: 'listing_7',
    title: 'Fiction Novel Bundles (Set of 3)',
    description: 'Choose any three fiction novels from my collection for a discounted price. Authors include Murakami, Adichie, and more. DM for the list.',
    category: 'Physical Products',
    price: 750,
    mediaUrl: findImage('listing-novels') || "https://picsum.photos/seed/listing7/600/400",
    mediaType: 'image',
    sellerId: 'user_3',
    seller: getListingSeller('user_3'),
    status: 'sold',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(),
    college: 'Delhi University',
  },
  {
    id: 'listing_9',
    title: 'Event Photography & Videography',
    description: 'Covering college events, birthdays, and workshops. I have a Sony A7III and can deliver edited photos within 48 hours.',
    category: 'Services',
    price: 3500,
    mediaUrl: findImage('listing-event-photography') || "https://picsum.photos/seed/listing9/600/400",
    mediaType: 'image',
    sellerId: 'user_2',
    seller: getListingSeller('user_2'),
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    college: 'Christ University, Bangalore',
  },
  {
    id: 'listing_10',
    title: 'Beginner Acoustic Guitar Lessons',
    description: 'One-on-one guitar lessons for beginners. Learn chords, strumming patterns, and your favorite songs. I have been playing for 5 years.',
    category: 'Services',
    price: 400,
    mediaUrl: findImage('listing-guitar-lessons') || "https://picsum.photos/seed/listing10/600/400",
    mediaType: 'image',
    sellerId: 'user_3',
    seller: getListingSeller('user_3'),
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
    college: 'Delhi University',
  },
  {
    id: 'listing_11',
    title: 'Scientific Calculator (CASIO fx-991ES PLUS)',
    description: 'Barely used scientific calculator, essential for engineering and science students. In perfect working condition with cover.',
    category: 'Physical Products',
    price: 600,
    mediaUrl: findImage('listing-calc-ra') || "https://picsum.photos/seed/listing11/600/400",
    mediaType: 'image',
    sellerId: 'user_1',
    seller: getListingSeller('user_1'),
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    college: 'IIT Bombay',
  },
  {
    id: 'listing_12',
    title: 'Wacom Drawing Tablet (One by Wacom)',
    description: 'Excellent condition drawing tablet, perfect for digital art beginners. Comes with the original pen and cable. Used for one semester.',
    category: 'Physical Products',
    price: 2500,
    mediaUrl: 'https://picsum.photos/seed/listing12/600/400',
    mediaType: 'image',
    sellerId: 'user_2',
    seller: getListingSeller('user_2'),
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    college: 'Christ University, Bangalore',
  },
  {
    id: 'listing_13',
    title: 'Resume & Cover Letter Review',
    description: 'Get your resume and cover letter reviewed before internship season. I have experience with placements and can help you stand out.',
    category: 'Services',
    price: 300,
    mediaUrl: 'https://picsum.photos/seed/listing13/600/400',
    mediaType: 'image',
    sellerId: 'user_1',
    seller: getListingSeller('user_1'),
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 9).toISOString(),
    college: 'IIT Bombay',
  },
  {
    id: 'listing_14',
    title: 'Looking for a Drummer and Bassist to form a Band',
    description: 'Vocalist and guitarist here, looking for a drummer and a bassist to form a rock/pop band. We practice on weekends. Let\'s jam!',
    category: 'Community/Collaboration',
    price: 0,
    mediaUrl: 'https://picsum.photos/seed/listing14/600/400',
    mediaType: 'image',
    sellerId: 'user_3',
    seller: getListingSeller('user_3'),
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
    college: 'Delhi University',
  },
  {
    id: 'listing_15',
    title: 'Stylish Study Table Lamp',
    description: 'A modern, minimalist LED table lamp. Perfect for late-night study sessions. It has adjustable brightness and a USB charging port.',
    category: 'Physical Products',
    price: 800,
    mediaUrl: findImage('listing-table-lamp') || 'https://picsum.photos/seed/listing15/600/400',
    mediaType: 'image',
    sellerId: 'user_2',
    seller: getListingSeller('user_2'),
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    college: 'Christ University, Bangalore',
  },
  {
    id: 'listing_16',
    title: 'Introduction to Sketching & Drawing',
    description: 'A 4-week beginner-friendly workshop on the fundamentals of sketching and drawing. No prior experience needed! All materials will be provided.',
    category: 'Services',
    price: 1200,
    mediaUrl: findImage('listing-drawing-tutoring') || 'https://picsum.photos/seed/listing16/600/400',
    mediaType: 'image',
    sellerId: 'user_3',
    seller: getListingSeller('user_3'),
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    college: 'Delhi University',
  },
  {
    id: 'listing_17',
    title: 'Set of 5 Classic Literature Books',
    description: 'Collection includes "Pride and Prejudice", "1984", "To Kill a Mockingbird", "The Great Gatsby", and "Moby Dick". All are paperback and in good condition.',
    category: 'Physical Products',
    price: 900,
    mediaUrl: findImage('listing-classic-books') || 'https://picsum.photos/seed/listing17/600/400',
    mediaType: 'image',
    sellerId: 'user_3',
    seller: getListingSeller('user_3'),
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
    college: 'Delhi University',
  },
  {
    id: 'listing_18',
    title: 'Mini-fridge for Hostel Room (50L)',
    description: 'A compact and silent mini-fridge, perfect for a hostel room. Used for one year, in great working condition. Brand is Godrej.',
    category: 'Physical Products',
    price: 4500,
    mediaUrl: findImage('listing-mini-fridge') || 'https://picsum.photos/seed/listing18/600/400',
    mediaType: 'image',
    sellerId: 'user_4',
    seller: getListingSeller('user_4'),
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
    college: 'IIT Madras',
  },
  {
    id: 'listing_19',
    title: 'Pigeon Electric Kettle (1.5L)',
    description: 'An electric kettle, very useful for making tea, coffee, or instant noodles. Selling because I got a new one. In perfect working order.',
    category: 'Physical Products',
    price: 400,
    mediaUrl: findImage('listing-electric-kettle') || 'https://picsum.photos/seed/listing19/600/400',
    mediaType: 'image',
    sellerId: 'user_5',
    seller: getListingSeller('user_5'),
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    college: 'NIFT Delhi',
  },
  {
    id: 'listing_20',
    title: 'Mi Power Bank 20000mAh',
    description: 'High-capacity power bank, can charge a phone multiple times. A must-have for students. Has two output ports. Lightly used.',
    category: 'Physical Products',
    price: 1200,
    mediaUrl: findImage('listing-power-bank') || 'https://picsum.photos/seed/listing20/600/400',
    mediaType: 'image',
    sellerId: 'user_1',
    seller: getListingSeller('user_1'),
    status: 'sold',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 50).toISOString(),
    college: 'IIT Bombay',
  },
  {
    id: 'listing_21',
    title: 'Online Coding Platform Subscription (6 months)',
    description: 'Selling a 6-month unused subscription voucher for a popular competitive programming platform. Great for interview prep. I got it as a prize.',
    category: 'Digital Products',
    price: 1800,
    mediaUrl: findImage('listing-coding-sub') || 'https://picsum.photos/seed/listing21/600/400',
    mediaType: 'image',
    sellerId: 'user_4',
    seller: getListingSeller('user_4'),
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    college: 'IIT Madras',
  },
];

export const dummyTransactions: Omit<Transaction, 'id'>[] = [
    {
        transactionId: 'txn_1',
        buyerId: 'user_2',
        sellerId: 'user_1',
        listingId: 'listing_3',
        amount: 1500,
        status: 'completed',
        paymentMethod: 'NexusCredits',
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 29).toISOString(),
    },
    {
        transactionId: 'txn_2',
        buyerId: 'user_1',
        sellerId: 'user_3',
        listingId: 'listing_7',
        amount: 750,
        status: 'completed',
        paymentMethod: 'NexusCredits',
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 44).toISOString(),
    },
    {
        transactionId: 'txn_3',
        buyerId: 'user_5',
        sellerId: 'user_1',
        listingId: 'listing_20',
        amount: 1200,
        status: 'completed',
        paymentMethod: 'NexusCredits',
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 49).toISOString(),
    }
];

export const dummyReviews: Omit<Review, 'id' >[] = [
    {
        listingId: 'listing_3',
        sellerId: 'user_1',
        buyerId: 'user_2',
        reviewerId: 'user_2',
        rating: 5,
        comment: 'Books were in perfect condition, just as described. Priya was super quick to respond and arrange the pickup. Highly recommend!',
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 28).toISOString(),
    },
    {
        listingId: 'listing_7',
        sellerId: 'user_3',
        buyerId: 'user_1',
        reviewerId: 'user_1',
        rating: 4,
        comment: 'Great collection of books! Ananya was very helpful. One of the book covers was a little worn, but otherwise a great deal.',
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 43).toISOString(),
    },
    {
        listingId: 'listing_20',
        sellerId: 'user_1',
        buyerId: 'user_5',
        reviewerId: 'user_5',
        rating: 5,
        comment: 'Power bank works perfectly and holds charge well. The transaction was smooth. Thanks Priya!',
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 48).toISOString(),
    }
];


    
