import type { User, Listing } from '@/lib/types';
import { PlaceHolderImages } from '@/lib/placeholder-images';

const findImage = (id: string) => PlaceHolderImages.find(img => img.id === id)?.imageUrl || '';

export const dummyUsers: User[] = [
  {
    id: 'user_1',
    name: 'Priya Sharma',
    email: 'priya@iitb.ac.in',
    college: 'IIT Bombay',
    bio: 'Budding software engineer and ML enthusiast. Selling my old engineering books and notes. Let\'s connect!',
    skills: ['Python', 'C++', 'Machine Learning', 'Data Structures'],
    profilePictureUrl: findImage('user-1') || "https://picsum.photos/seed/user1/200",
    role: 'student',
    following: ['user_2'],
    followers: ['user_3'],
  },
  {
    id: 'user_2',
    name: 'Rohan Mehta',
    email: 'rohan@christuniversity.in',
    college: 'Christ University, Bangalore',
    bio: 'BBA student with a passion for marketing and graphic design. Offering freelance design services for college fests and events.',
    skills: ['Graphic Design', 'Canva', 'Social Media Marketing'],
    profilePictureUrl: findImage('user-2') || "https://picsum.photos/seed/user2/200",
    role: 'student',
    following: [],
    followers: ['user_1', 'user_3'],
  },
  {
    id: 'user_3',
    name: 'Ananya Singh',
    email: 'ananya@du.ac.in',
    college: 'Delhi University',
    bio: 'Aspiring journalist and avid reader. Selling curated bundles of pre-loved novels and providing proofreading services.',
    skills: ['Writing', 'Editing', 'Content Creation'],
    profilePictureUrl: findImage('user-3') || "https://picsum.photos/seed/user3/200",
    role: 'student',
    following: ['user_1', 'user_2'],
    followers: [],
  },
];

export const dummyListings: Listing[] = [
  {
    id: 'listing_1',
    title: 'GATE CSE Digital Preparation Notes',
    description: 'Comprehensive and well-organized digital notes for all Computer Science subjects for the GATE exam. Includes solved previous year papers.',
    category: 'Digital Products',
    price: 499.00,
    mediaUrl: findImage('listing-gate-notes'),
    mediaType: 'image',
    sellerId: 'user_1',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    college: 'IIT Bombay',
  },
  {
    id: 'listing_2',
    title: 'Graphic Design for College Fests',
    description: 'Need posters, social media posts, or logos for your college event? I provide professional design services at student-friendly prices. Contact for a quote.',
    category: 'Services',
    price: 999.00,
    mediaUrl: findImage('listing-fest-design'),
    mediaType: 'image',
    sellerId: 'user_2',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    college: 'Christ University, Bangalore',
  },
  {
    id: 'listing_3',
    title: 'Gently Used Engineering Textbooks (1st Year)',
    description: 'Complete set of first-year engineering textbooks for CSE. Includes books for Physics, Chemistry, Maths, and C++. All in excellent condition.',
    category: 'Physical Products',
    price: 1500.00,
    mediaUrl: findImage('listing-engg-books'),
    mediaType: 'image',
    sellerId: 'user_1',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
    college: 'IIT Bombay',
  },
  {
    id: 'listing_4',
    title: 'Need Teammate for Smart India Hackathon',
    description: 'Looking for a backend developer (Node.js/Django) for our team for the Smart India Hackathon. We have a great idea for a healthcare solution.',
    category: 'Community/Collaboration',
    price: 0.00,
    mediaUrl: findImage('listing-hackathon'),
    mediaType: 'image',
    sellerId: 'user_1',
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    college: 'IIT Bombay',
  },
  {
    id: 'listing_5',
    title: 'Homemade North Indian Tiffin Service',
    description: 'Delicious and healthy home-cooked North Indian meals delivered to your hostel or PG. Weekly and monthly plans available. (Only for IITB campus)',
    category: 'Services',
    price: 120.00,
    mediaUrl: findImage('listing-tiffin'),
    mediaType: 'image',
    sellerId: 'user_3',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    college: 'Delhi University',
  },
  {
    id: 'listing_8',
    title: 'Used Bicycle for Campus Commute',
    description: 'A Hero cycle in good working condition. Perfect for getting around the large DU campus. Minor scratches but runs smoothly. Price is negotiable.',
    category: 'Physical Products',
    price: 2000,
    mediaUrl: findImage('listing-bicycle'),
    mediaType: 'image',
    sellerId: 'user_3',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
    college: 'Delhi University',
  },
  {
    id: 'listing_7',
    title: 'Fiction Novel Bundles (Set of 3)',
    description: 'Choose any three fiction novels from my collection for a discounted price. Authors include Murakami, Adichie, and more. DM for the list.',
    category: 'Physical Products',
    price: 750,
    mediaUrl: findImage('listing-novels'),
    mediaType: 'image',
    sellerId: 'user_3',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
    college: 'Delhi University',
  },
];
